#!/usr/bin/env python3
# -*- mode: python-mode;
# coding: utf-8

import daemon

import argparse

from src.service import *


def run():
    app = tornado.web.Application(
        [
            (r'/', Index),
            (r'/bump', Service),
            (r'/anonstat.js', Script),
            (r'/widget.png', Widget),
            (r"/css/(.*)", tornado.web.StaticFileHandler,
             {"path": "./dashboard/css/"}),
            (r"/js/(.*)", tornado.web.StaticFileHandler,
             {"path": "./dashboard/js/"}),
        ],
        cookie_secret=cookie_secret
    )
    app.listen(cfg.port)
    tornado.ioloop.IOLoop.current().start()


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument('-c', '--config', action='store',
                        help='Specify configuration file, \'./config.py\' by default')
    parser.add_argument('-d', '--daemon', action='store_true',
                        help='Run as a daemon')
    parser.add_argument('-l', '--logfile', action='store',
                        help='Specify a log file, defaults depend on mode,'
                        'if it\'s a daemon-mode, then /dev/null is used, stdout/stderr otherwise')
    parser.add_argument('-e', '--debug', action='store_true',
                        help='Set logging level to DEBUG')

    args = parser.parse_args()

    log = open(args.logfile, 'a') if args.logfile else None
    if args.config:
        cfg = imp.load_source('cfg', args.config)
    logger = tornado.log.logging.getLogger()
    if args.debug:
        logger.setLevel(tornado.log.logging.DEBUG)
    else:
        logger.setLevel(tornado.log.logging.FATAL)
    if args.daemon:
        with daemon.DaemonContext(working_directory=os.path.dirname(os.path.abspath(__file__)),
                                  stdout=log, stderr=log):
            run()
    else:
        run()
