#!/usr/bin/env python3
# -*- mode: python-mode;
# coding: utf-8
import sys

sys.path.append('./src/')
from service import *

if __name__ == "__main__":
    app = tornado.web.Application(
        [
            (r'/', Index),
            (r'/bump', Service),
            (r'/anonstat.js', Script),
            (r'/widget.png', Widget)
        ],
        template_path=os.path.join(os.path.dirname(__file__), "templates"),
        cookie_secret=cookie_secret

    )
    app.listen(cfg.port)
    tornado.ioloop.IOLoop.current().start()
